site_2/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns =[
    path('',views.home,name='home'),
    path('profile/',views.all_profile,name='profile'),
    path('test/',views.profile_link_homepage),
    path('create_post/',views.post,name='post'),
    path('like_post/<int:id>/',views.like_post,name='like'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('comment/<int:id>/',views.post_comment,name='comment'),
    path('search/',views.search,name='search')
    
]

site_2/register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns =[
     path ('',views.index,name='register'),
     path('step2/',views.index_2,name='next_step'),
     path('login/',views.login,name='login'),
     path('profile/<int:id>/',views.userprofile,name='profile'),
     path('update/',views.ProfileUpdate,name='update'),
     path('change/',views.changepassword,name='change'),
     path('logout/',views.logoutuser,name='logout'),
     path('follow/<int:id>/',views.follow_user,name='follow')

]

site_2/site_2/urls.py
from django.contrib import admin
from django.urls import path,include
from home import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('register/',include('register.urls')),
    path('api/',include('home.api.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_2/register/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.
class profile(models.Model):
    user =  models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.IntegerField(null=True,blank=True)
    addres= models.CharField(max_length=200,null=True,blank=True)
    bio = models.CharField(max_length=100,null=True,blank=True)
    birth = models.DateField(null=True,blank=True)
    img=models.ImageField(upload_to='profile_img',null=True,blank=True)
    follow = models.ManyToManyField(User,blank=True,null=True,related_name='follow')
    follow_counter = models.PositiveBigIntegerField(default=0)
    def follow_counter(self):
        return self.follow.count()
def saveorifuleuser(sender ,**kwargs):
    if kwargs.get('created'):
        profileuser=profile(user=kwargs.get('instance'))
        profileuser.save()


post_save.connect(saveorifuleuser,sender=User)

site_2/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import profile

class register_form(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    class meta:
        model = User
        fields = ('username','email,','password','first_name','last_name')

    def save(self,commit=True):
        user = super(register_form,self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

class userlogin(forms.Form):
    username=forms.CharField(max_length=100,widget=forms.TextInput(attrs={'placeholder':'Email or Username'}))
    password=forms.CharField(max_length=100,widget=forms.PasswordInput(attrs={'placeholder':'Password'}))

class userupdateform(forms.ModelForm):
    class Meta:
        model= User
        fields = ['email','first_name','last_name']
    
class profileupdateform(forms.ModelForm):
    class Meta:
        model = profile
        fields =['phone','addres','birth','bio','img']


    

site_2/register/views.py
from django.shortcuts import render,redirect,get_object_or_404

from home.models import Post
from .forms import *
from django.contrib.auth import authenticate,login as aa,logout
from django.contrib import messages
from .models import profile 
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages 
# Create your views here.

def  index (request):
    if request.method == 'POST':
        form = register_form(request.POST)
        if  form.is_valid():
          user = form.save()
          aa(request,user)
          messages.success(request,'Next step')
          return redirect('register:next_step')
        messages.error(request,'Unsuccessful registration. Invalid information.')
    form = register_form()
    return render(request,'register.html',{'form':form})    
def index_2(request):
    if request.method =='POST':
        profile_form = profileupdateform(request.POST,request.FILES,instance=request.user.profile)
        if  profile_form.is_valid():
            profile_form.save()
            messages.success(request,'register successfully')
            return redirect('home:home')
    else:
        profile_form = profileupdateform(instance=request.user.profile)
    return render(request,'next_step.html',{'profile_form':profile_form})
    
def login (request):
    if request.method == 'POST':
        form = userlogin(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                 user = authenticate(request,username=User.objects.get(email=data['username']), password=data['password'])
            except:
                 user = authenticate(request,username=data['username'], password=data['password'])

            if user is not None:
                aa(request,user)
                messages.success(request,'your succsesfuly login')
                return redirect('home:home')
            else:
                messages.error(request,' username or passwors is incorrect')
    else:
        form=userlogin()
    return render (request,'login.html',{'form':form})


@login_required(login_url='register:login')
def userprofile(request,id):
    pro = get_object_or_404(profile,id=id)
    user_posts = Post.objects.filter(user_id= pro.user.id)
    show_followers = profile.follow
    is_follow = False
    if pro.follow.filter(id = request.user.id).exists():
        is_follow=True
    return render(request,'profile.html',{'pro':pro,'is_follow':is_follow,'show_followers':show_followers , 'user_posts':user_posts})
@login_required(login_url='register:login')
def ProfileUpdate(request):
    if request.method =='POST':
        user_form = userupdateform(request.POST,instance=request.user)
        profile_form = profileupdateform(request.POST,request.FILES,instance=request.user.profile)
        if user_form and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'update successfully')
            return redirect('home:home')
    else:
        user_form = userupdateform(instance=request.user)
        profile_form = profileupdateform(instance=request.user.profile)
    return render(request,'update.html',{'user_form':user_form,'profile_form':profile_form})
@login_required(login_url='home:home')
def changepassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success(request,'Password changes','SUCCESS')
            return redirect('register:profile')
        else:
            messages.error(request,'something went wrong, try again')
            return redirect('register:change')

    else:
        form = PasswordChangeForm(request.user)
    return  render(request,'change.html',{'form':form})

def logoutuser(request):
    logout(request)
    messages.success(request,'loged out')
    return redirect('home:home')

def follow_user(request,id):
    follower = get_object_or_404(profile,id=id)
    is_follow = False
    if follower.follow.filter(id=request.user.id).exists():
        follower.follow.remove(request.user)
        is_follow = False
        messages.success(request,'you unfollow this user')
    else: 
        follower.follow.add(request.user)
        is_follow = True
        messages.success(request,'you follow this user')

    return redirect ('register:profile',follower.id)

site_2/register/templates/change.html
{%extends 'base.html'%}
{%block body%}
{%include 'messages.html'%}
<form action="" method="POST">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">change</button>
</form>
{%endblock%}

site_2/register/templates/login.html
{%extends 'base.html'%}

{% block body%}
   
<style>
    form {
    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px; 
}
</style>



<form method="POST">
    {%csrf_token%}
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="username" >
        <label for="floatingInput">User name</label>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" name="password">
        <label for="floatingPassword">Password</label>
      </div>
      <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

 
  {%endblock%}

site_2/register/templates/next_step.html
{%extends 'base.html'%}
{% block body%}
<head>
    <style>
    form {

        margin-top: 100px;
        margin-bottom: 100px;
        margin-right: 150px;
        margin-left: 80px;
    }
</style>
</head>
<body>
<form method="post" enctype="multipart/form-data">
 {% csrf_token%}
 <div class="mb-3">
    <label class="form-label">Birth</label>
    <input type="text" class="form-control" name="birth">
  </div>
 <div class="mb-3">
    <label class="form-label">Phone</label>
    <input type="number" class="form-control" name="Phone">
  </div>
  <div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="addres">
  </div>
  <div class="mb-3">
    <label class="form-label">Bio</label>
    <input type="text" class="form-control" name="bio">
  </div>
  <div class="mb-3">
    <label class="form-label">Image:</label>
    <input type="file" id="imagefile" accept="image/*" name="img">
  </div>
<button type="submit" class="btn btn-primary">Complete</button>
</form>

</body>
{%endblock%}

site_2/register/templates/profile.html
{% extends 'base.html'%}
{%block  body%}

<title>instagram sample</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
        <!-- Profile -->
        <div class="w3-card w3-round w3-white">
          <div class="w3-container">
           <h4 class="w3-center">{{pro.user.first_name}} {{pro.user.last_name}}</h4>
           <p class="w3-center"><img src="{{pro.img.url}}" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
           <p>
            {%if is_follow%}
            <a  href="{%url 'register:follow' pro.id%}"  class="w3-button w3-theme-d2 w3-margin-bottom" style="margin-inline: 3px;">Unfollow</a>
            {%else%}
            <a  href="{%url 'register:follow' pro.id%}"  class="w3-button w3-theme-d2 w3-margin-bottom">Follow</a>
            {%endif%}
            <a  href="#"  class="w3-button w3-theme-d2 w3-margin-bottom" >Message</a>
          </p>
           
            <hr>
           <a  data-bs-toggle="collapse" href="#collapsefollow" role="button" aria-expanded="false" aria-controls="collapseExample">
            <p><i class="fa fa-user fa-fw w3-margin-right w3-text-theme"></i>followers: {{pro.follow_counter}}</p>
          </a>
          <div class="collapse" id="collapsefollow">
            {%for i in pro.follow.all%}
            <div class="card card-body">
              <p>
                <img src="{{i.profile.img.url}}" class="w3-circle" style="height:50px;width:50px" alt="Avatar"> <a href="{%url 'register:profile' i.profile.id%}">{{i.username}} </a>
            </p> 
             </div>
             {%endfor%}
          </div>
           <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> {{pro.bio}}</p>
           <p><i class="fa fa-phone fa-fw w3-margin-right w3-text-theme"></i> {{pro.phone}}</p>
           <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{pro.addres}}</p>
           <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> {{pro.birth}}</p>
          </div>
        </div>
        <br>
<div class="container">
  <div class="row">
{%for i in user_posts%}
<div class="card" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p class="card-text">{{i.text}}</p>
    <a href="{%url 'home:detail' i.id%}" class="w3-button w3-theme-d2 w3-margin-bottom" >Detail</a>
  </div>
</div>
{%endfor%}
</div>
</div>
{%endblock%}

site_2/register/templates/register.html
{% extends 'base.html'%}
{%block body%}
<style>
    ul {
        display: none;
    }
    form {

    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
}
</style>
<body>
<form method="POST" novalidate>
           {%csrf_token%}
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">User name</label>
              <input type="text" class="form-control" name="username">
              <div  class="form-text">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" name="password1">
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password confirmation</label>
              <input type="password" class="form-control" name="password2">
              <div class="form-text">Enter the same password as before, for verification.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Email address</label>
              <input type="email" class="form-control" name="email" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">First name</label>
              <input type="text" class="form-control" name="first_name">
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Last name</label>
              <input type="text" class="form-control" name="last_name">
            </div>
          
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Next</button>
            </form>>
    </body>
{% endblock%}

site_2/register/templates/update.html
{%extends 'base.html'%}
{% block body%}
<head>
    <style>
    form {

        margin-top: 100px;
        margin-bottom: 100px;
        margin-right: 150px;
        margin-left: 80px;
    }
</style>
</head>
<body>
<form method="post" enctype="multipart/form-data">
 {% csrf_token%}
{{user_form.as_p}}
{{profile_form.as_p}}
<button type="submit">Update</button>
</form>

{%endblock%}