site_2/home/api/urls.py
from django.urls import path
from . import views

name = 'api'
urlpatterns = [
    path('',views.post_list_api_view.as_view(),name='api_list'),
    path('detail/<int:id>/',views.post_detail_api_view.as_view(),name='api_detail'),
    path('<int:id>/delete/',views.post_delete_api_view.as_view(),name='api_delete'),
    path('<int:id>/update/',views.post_update_api_view.as_view(),name='api_update'),
    path('create/',views.post_create_api_view.as_view(),name='api_create'),
]

site_2/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns =[
    path('',views.home,name='home'),
    path('profile/',views.all_profile,name='profile'),
    path('test/',views.profile_link_homepage),
    path('create_post/',views.post,name='post'),
    path('like_post/<int:id>/',views.like_post,name='like'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('comment/<int:id>/',views.post_comment,name='comment'),
    path('search/',views.search,name='search')
    
]

site_2/register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns =[
     path ('',views.index,name='register'),
     path('step2/',views.index_2,name='next_step'),
     path('login/',views.login,name='login'),
     path('profile/<int:id>/',views.userprofile,name='profile'),
     path('update/',views.ProfileUpdate,name='update'),
     path('change/',views.changepassword,name='change'),
     path('logout/',views.logoutuser,name='logout'),
     path('follow/<int:id>/',views.follow_user,name='follow')

]

site_2/site_2/urls.py
from django.contrib import admin
from django.urls import path,include
from home import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('register/',include('register.urls')),
    path('api/',include('home.api.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_2/home/models.py
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from .models import *

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=1000)
    img = models.ImageField(upload_to='post_img')
    like = models.ManyToManyField(User,blank=True,null=True,related_name='post_like')
    like_counter = models.PositiveBigIntegerField(default=0)

    
    def like_counter(self):
        return self.like.count()


class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    poost = models.ForeignKey(Post,on_delete=models.CASCADE)
    comment = models.TextField()
    create = models.DateTimeField(auto_now_add=True)



    

site_2/home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
from django.forms import ModelForm
class post_form(forms.ModelForm):
    class Meta:
        model= Post
        fields = ['img','text']
class commentform(ModelForm):
    class Meta:
        model = Comment
        fields=['comment'] 

class searchform(forms.Form):
    search = forms.CharField(max_length=20)

site_2/home/api/views.py
from django.db.models.query import QuerySet
from rest_framework import generics
from rest_framework.serializers import Serializer
from home.models import Post
from  . serializers import *

class post_list_api_view(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = postserializer

class post_detail_api_view(generics.RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = postdetailserializer
    lookup_field = 'id'


class post_delete_api_view(generics.DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = postdeleteserializer
    lookup_field = 'id'

class post_update_api_view(generics.UpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = postupdateserializer
    lookup_field = 'id'

class post_create_api_view(generics.CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = postupdateserializer
    

site_2/home/views.py
from typing import Text
from django.http import request
from .models import Post
from django.shortcuts import render,redirect,get_object_or_404
from register.models import profile
from django.contrib.auth.decorators import login_required
from django.contrib import messages as pm
from .forms import *
from django.db.models import Q

@login_required(login_url='register:login')
def home(request):
    post = Post.objects.all().order_by('-time')
    pro = profile.objects.get(user_id = request.user.id)
    form = post_form()
    show = Post.like
    return render(request,'home.html',{'pro':pro,'post':post,'form':form,'show':show})

@login_required(login_url='register:login')
def all_profile(request):
    pro = profile.objects.all()
    return render(request,'all_profile.html',{'pro':pro})

def profile_link_homepage(request,id):
    link = profile.objects.get(id=id)
    return render (request,'test.html',{'link':link})


def post(request):
    if request.method =='POST':
        form = post_form(request.POST,request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            Post.objects.create(text=data['text'],img=data['img'],user_id=request.user.id)
        return redirect('home:home')


def like_post(request,id):
    post = get_object_or_404(Post,id=id)
    is_like = False
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        is_like = False
        pm.success(request,'you disliked this post')
    else: 
        post.like.add(request.user)
        is_like = True
        pm.success(request,'you liked this post')

    return redirect ('home:detail',post.id)
    
def detail(requset,id):
    post = get_object_or_404(Post,id=id)
    show_like = post.like.all()
    comment_from = commentform()
    comment = Comment.objects.filter(poost_id=id,)
    is_like = False
    if post.like.filter(id=requset.user.id).exists():
        is_like=True
    return render(requset,'detail.html',{'show_like':show_like,'post':post,'is_like':is_like,'comment_from':comment_from,'comment':comment})
def post_comment(request,id):
        post = get_object_or_404(Post,id=id)
        comment_form=commentform(request.POST)
        if comment_form.is_valid():
            data = comment_form.cleaned_data
            Comment.objects.create(comment=data['comment'],user_id=request.user.id,poost_id=id) 
        return redirect('home:detail',post.id)

def search(request):
    post = Post.objects.all()
    if request.method == 'POST':
        form = searchform(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']
            if data is not None:
                post=Post.objects.filter(text__contains=data)
            return render(request,'all_profile.html',{'post':post,'form':form})

site_2/home/templates/all_profile.html
{% extends 'base.html'%}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static 'home/all.css'%}">
{%endblock%}
{%block body%}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
.main {
    width: 50%;
    margin: 50px auto;
}

/* Bootstrap 4 text input with search icon */

.has-search .form-control {
    padding-left: 2.375rem;
}

.has-search .form-control-feedback {
    position: absolute;
    z-index: 2;
    display: block;
    width: 2.375rem;
    height: 2.375rem;
    line-height: 2.375rem;
    text-align: center;
    pointer-events: none;
    color: #aaa;
}

</style>
<body>

  <div class="main">
  

    <div class="input-group">
      <form method="POST" action="{%url 'home:search'%}">
        {%csrf_token%}
      <input type="text" class="form-control" placeholder="Search this blog" name="search">
      <div class="input-group-append">
        <button class="btn btn-secondary" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </form>
  </div>
  
  
  <div class="container">
    <div class="row">
      {%for i in post%}
  <div class="card" style="width: 18rem;">
    <img src="{{i.img.url}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title"></h5>
      <p class="card-text">{{i.text}}</p>
      <a href="{%url 'home:detail' i.id%}" class="w3-button w3-theme-d2 w3-margin-bottom" >Detail</a>
    </div>
  </div>
  {%endfor%}
  </div>
  </div>

  
</body>
{%endblock%}

site_2/home/templates/detail.html
{%extends 'base.html'%}

{%block body%}
<title>instagram sample</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1"> 
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
<body class="w3-theme-l5">
<div class="w3-container w3-card w3-white w3-round w3-margin"><br>
  <a href="{%url 'register:profile' post.user.profile.id%}"> <img src="{{post.user.profile.img.url}}" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px"></a>
  <span class="w3-right w3-opacity">{{post.time}}</span>  
 <a href="{%url 'register:profile' post.user.profile.id%}">  <h4>{{post.user.first_name}} {{post.user.last_name}}</h4><br></a>
  <hr class="w3-clear">
  
    <div class="w3-row-padding" style="margin:0 -16px">
      <div class="w3-half">
        <img src="{{post.img.url}}" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
        <p>{{post.text}}</p>
        </div>
      </div>
{%if is_like%}
<a  href="{%url 'home:like' post.id%}"  class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-thumbs-down"></i></a>
{%else%}
  <a  href="{%url 'home:like' post.id%}"  class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-thumbs-up"></i></a>
  {%endif%}
    <a class="w3-button w3-theme-d2 w3-margin-bottom" data-bs-toggle="collapse" href="#collapseLike" role="button" aria-expanded="false" aria-controls="collapseExample">
      {{post.like_counter}} like
    </a>
    <div class="collapse" id="collapseLike">
      {%for i in post.like.all%}
      <div class="card card-body">
        <p>
          <img src="{{i.profile.img.url}}" class="w3-circle" style="height:50px;width:50px" alt="Avatar"> <a href="{%url 'register:profile' i.profile.id%}">{{i.username}} </a>
      </p> 
       </div>
       {%endfor%}
    </div>
    <a class="w3-button w3-theme-d2 w3-margin-bottom" data-bs-toggle="collapse" href="#collapseComment" role="button" aria-expanded="false" aria-controls="collapseExample">
      Comment
    </a>
    <div class="collapse" id="collapseComment">
      <div class="card card-body">
        <form method="POST" action="{%url 'home:comment' post.id%}">
          {%csrf_token%}
          <div class="comment-box">
            <textarea name="comment" class="form-control" rows="4"></textarea>
          </div>
          <button type="submit" class="w3-button w3-theme-d2 w3-margin-bottom">submit comment</button>
        </form>
        {%for i in comment%}
        <div class="col-8">
          <p>  <img src="{{i.user.profile.img.url}}" class="w3-circle" style="height:40px;width:40px" alt="Avatar"> <a href="{%url 'register:profile' i.user.profile.id%}">{{i.user.username}} </a>: {{i.comment}} 

       </div>
       {%endfor%}
    </div>
  
</div>

</body>
{%endblock%}




<div class="comment-box">
  <textarea name="comment" class="form-control" rows="4"></textarea>
</div>
<button type="submit" class="btn btn-danger">ثبت کامنت</button>

site_2/home/templates/home.html
{% extends 'base.html'%}
{%if pro%}
{%block body%}

<title>instagram sample</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
<body class="w3-theme-l5">

<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
          
       <a href="{%url 'register:profile' pro.user.profile.id%}" ><h4 class="w3-center">{{pro.user.first_name}} {{pro.user.last_name}}</h4></a> 
       <a href="{%url 'register:profile' pro.user.profile.id%}" >  <p class="w3-center"><img src="{{pro.img.url}}" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p></a>
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> {{pro.bio}}</p>
         <p><i class="fa fa-phone fa-fw w3-margin-right w3-text-theme"></i> {{pro.phone}}</p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> {{pro.addres}}</p>
         <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> {{pro.birth}}</p>
        </div>
      </div>
      <br>
    
     <!-- Accordion -->
      <div class="w3-card w3-round">
        <div class="w3-white">
          <button onclick="myFunction('Demo1')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-circle-o-notch fa-fw w3-margin-right"></i> My Groups</button>
          <div id="Demo1" class="w3-hide w3-container">
            <p>Some text..</p>
          </div>
          <button onclick="myFunction('Demo2')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-calendar-check-o fa-fw w3-margin-right"></i> My Events</button>
          <div id="Demo2" class="w3-hide w3-container">
            <p>Some other text..</p>
          </div>
          <button onclick="myFunction('Demo3')" class="w3-button w3-block w3-theme-l1 w3-left-align"><i class="fa fa-users fa-fw w3-margin-right"></i> My Photos</button>
          <div id="Demo3" class="w3-hide w3-container">
         <div class="w3-row-padding">
         <br>
           <div class="w3-half">
             <img src="/w3images/lights.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/mountains.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/forest.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
           <div class="w3-half">
             <img src="/w3images/snow.jpg" style="width:100%" class="w3-margin-bottom">
           </div>
         </div>
          </div>
        </div>      
      </div>
      <br>
      
      <!-- Interests --> 
      <div class="w3-card w3-round w3-white w3-hide-small">
        <div class="w3-container">
          <p>Interests</p>
          <p>
            <span class="w3-tag w3-small w3-theme-d5">News</span>
            <span class="w3-tag w3-small w3-theme-d4">W3Schools</span>
            <span class="w3-tag w3-small w3-theme-d3">Labels</span>
            <span class="w3-tag w3-small w3-theme-d2">Games</span>
            <span class="w3-tag w3-small w3-theme-d1">Friends</span>
            <span class="w3-tag w3-small w3-theme">Games</span>
            <span class="w3-tag w3-small w3-theme-l1">Friends</span>
            <span class="w3-tag w3-small w3-theme-l2">Food</span>
            <span class="w3-tag w3-small w3-theme-l3">Design</span>
            <span class="w3-tag w3-small w3-theme-l4">Art</span>
            <span class="w3-tag w3-small w3-theme-l5">Photos</span>
          </p>
        </div>
      </div>
      <br>
      
      <!-- Alert Box -->
      <div class="w3-container w3-display-container w3-round w3-theme-l4 w3-border w3-theme-border w3-margin-bottom w3-hide-small">
        <span onclick="this.parentElement.style.display='none'" class="w3-button w3-theme-l3 w3-display-topright">
          <i class="fa fa-remove"></i>
        </span>
        <p><strong>Hey!</strong></p>
        <p>People are looking at your profile. Find out who.</p>
      </div>
    
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
      <form method="post" enctype="multipart/form-data" action="{%url 'home:post'%}">
        {%csrf_token%}
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <div class="mb-3">
                <input type="file" id="imagefile" accept="image/*" name="img">
              </div>
              <h6 class="w3-opacity">Social Media template by w3.css</h6>
              <div class="mb-3">
                <input type="text" class="form-control" name="text">
              </div>
              <button type="submit" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  Post</button> 
            </div>
          </div>
        </div>
      </form>
      </div>
      {%for i in post%}
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <a href="{%url 'register:profile' i.user.profile.id%}"> <img src="{{i.user.profile.img.url}}" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px"></a>
        <span class="w3-right w3-opacity">{{i.time}}</span>  
       <a href="{%url 'register:profile' i.user.profile.id%}">  <h4>{{i.user.first_name}} {{i.user.last_name}}</h4><br></a>
        <hr class="w3-clear">
        
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half">
              <img src="{{i.img.url}}" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
              <p>{{i.text}}</p>
              </div>
            </div>

        <a href="{%url 'home:detail' i.id%}" class="w3-button w3-theme-d2 w3-margin-bottom">Detail</a>

      </div>
     
    
      {%endfor%}
    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Upcoming Events:</p>
          <img src="/w3images/forest.jpg" alt="Forest" style="width:100%;">
          <p><strong>Holiday</strong></p>
          <p>Friday 15:00</p>
          <p><button class="w3-button w3-block w3-theme-l4">Info</button></p>
        </div>
      </div>
      <br>
      
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Friend Request</p>
          <img src="/w3images/avatar6.png" alt="Avatar" style="width:50%"><br>
          <span>Jane Doe</span>
          <div class="w3-row w3-opacity">
            <div class="w3-half">
              <button class="w3-button w3-block w3-green w3-section" title="Accept"><i class="fa fa-check"></i></button>
            </div>
            <div class="w3-half">
              <button class="w3-button w3-block w3-red w3-section" title="Decline"><i class="fa fa-remove"></i></button>
            </div>
          </div>
        </div>
      </div>
      <br>
      
      <div class="w3-card w3-round w3-white w3-padding-16 w3-center">
        <p>ADS</p>
      </div>
      <br>
      
      <div class="w3-card w3-round w3-white w3-padding-32 w3-center">
        <p><i class="fa fa-bug w3-xxlarge"></i></p>
      </div>
      
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>

<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
  <h5>Footer</h5>
</footer>

<footer class="w3-container w3-theme-d5">
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>
 
<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else { 
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html> 
{%endblock%} 
{%endif%}

site_2/home/templates/post.html
{% extends 'base.html'%}
<style>

    form {

    margin-top: 100px;
    margin-bottom: 100px;
    margin-right: 150px;
    margin-left: 80px;
}
</style>
<body>
{%block body%}
<form method="POST" novalidate>
    {%csrf_token%}
    <div class="mb-3">
        <label class="form-label">Image:</label>
        <input type="file" id="imagefile" accept="image/*" name="img">
      </div>
     <div class="mb-3">
    <input type="text" class="form-control" name="text">
     </div>
     <button type="submit" class="btn btn-primary">post</button>
</form>
</body>
{%endblock%}