site_2/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns =[
    path('',views.home,name='home'),
    path('profile/',views.all_profile,name='profile'),
    path('test/',views.profile_link_homepage),
    path('create_post/',views.post,name='post'),
    path('like_post/<int:id>/',views.like_post,name='like'),
    path('detail/<int:id>',views.detail,name='detail'),
    path('comment/<int:id>/',views.post_comment,name='comment'),
    path('search/',views.search,name='search')
    
]

site_2/register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns =[
     path ('',views.index,name='register'),
     path('step2/',views.index_2,name='next_step'),
     path('login/',views.login,name='login'),
     path('profile/<int:id>/',views.userprofile,name='profile'),
     path('update/',views.ProfileUpdate,name='update'),
     path('change/',views.changepassword,name='change'),
     path('logout/',views.logoutuser,name='logout'),
     path('follow/<int:id>/',views.follow_user,name='follow')

]

site_2/site_2/urls.py
from django.contrib import admin
from django.urls import path,include
from home import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
    path('register/',include('register.urls')),
    path('api/',include('home.api.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_2/templates/base.html
<!DOCTYPE html>
<html>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  
 
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
        <div class="container-fluid">
          {% if user.is_authenticated%}
          <div class="btn-group">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">{{user.username}}</button>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{%url 'register:update'%}"><i class="fa fa-user"></i> Update profile</a></li> 
              <li><a class="dropdown-item" href="{%url 'register:change'%}"><i class="fa fa-key"></i> Change password</a></li>
              <li><a class="dropdown-item" href="#"><i class="fa fa-gear"></i> setting</a></li> 
              <li><a class="dropdown-item"href="{%url 'register:logout'%}"><i class="fa fa-sign-out"></i> Logout</a></li>
          </div>
          {%else%}
          <a class="navbar-brand" href="{% url 'register:login'%}"><h6>signin</h6></a>
          <a class="navbar-brand" href="{% url 'register:register'%}"><h6>signup</h6></a>
          {%endif%}
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{%url 'home:home'%}"><i class="fa fa-home"></i></a>
              <a class="nav-link active" href="{%url 'home:profile'%}"><i class="fa fa-globe"></i></a>
              <a class="nav-link active" href="#"><i class="fa fa-envelope"></i></a>
              <a class="nav-link active"><i class="fa fa-bell"></i></a>
            </div>
          </div>
          <iframe src="https://free.timeanddate.com/clock/i80j731b/n246/fcfff/tc000/tt0/tw0/tm1/th1/ts1/tb4" frameborder="0" width="87" height="34"></iframe>
        </div>
      </nav>
      <head>
        {%block css%} {%endblock%}
      </head>
    <body>
        {%include 'messages.html'%}
        {%block body%}
        {%endblock %}
    </body>
  
</html>

site_2/templates/messages.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">    </head>
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
    </symbol>
    <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
    </symbol>
    <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
      <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </symbol>
  </svg>
{% if messages%}
{% for msg in messages%}
<div class="alert alert-primary d-flex align-items-center" role="alert">
  <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
  <div>
    {{msg}}
  </div>
</div>
{% endfor%}
{% endif%}